/ros2_imu_node:
  ros__parameters:
    # mode zyz/atk
    imu_module: "zyz"
    # IMU端口
    imu_port: "/dev/imu_port"
    # 波特率
    baudrate: 115200
    # 1帧数据长度
    data_len: 24
    # 话题名称
    topic: "imu_data"
    # frame_id
    imu_frame_id: "imu_link"
