/ros2_imu_node:
  ros__parameters:
    # mode zyz/atk
    imu_module: "atk"
    # IMU端口
    imu_port: "/dev/ttyS7"
    # IMU中断脚
    imu_int: "/dev/input/event5"
    # 波特率 921600
    baudrate: 921600
    # 1帧数据长度
    data_len: 121
    # 话题名称
    topic: "imu_data"
    # frame_id
    imu_frame_id: "imu_link"