/ros2_imu_node:
  ros__parameters:
    imu:
      # mode zyz/atk
      module: "mpu6050"
      # IMU端口
      port: "/dev/i2c-5"
      # 波特率
      baudrate: 400000
      # 中断脚
      interupt:
        chip: "/dev/gpiochip1"
        line: 4
    # 1帧数据长度
    data_len: 121
    # 话题名称
    topic: "imu_data"
    # frame_id
    imu_frame_id: "imu_link"